# sensors-service/sensorEmulator/Dockerfile
# Establecer la imagen base
FROM node:14

# Crear y establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Comando para ejecutar el emulador
CMD ["ts-node", "sensorEmulator.ts"]
