# Base image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install
RUN npm install -g ts-node

# Copy source code
COPY . .

# Expose port
EXPOSE 3010
EXPOSE 9240

# Start the gateway with inspector
CMD [ "npm", "run", "start" ]
